### ISSUE TITLE
Do you have a plan to open training code?

### ISSUE THREAD

**Issue by craggy-otake** [NL2Code/CodeM#3]
Thanks you for nice work.

These days, I try to replicate the experiment. Do you have a plan to open training code? Is it the same as alpaca?

**Comment by TsukimiRini** [comment]
Hi, thank you for your interest in our work.
Unfortunately, the training code will not be made available due to company policy. But You can use any training framework like DeepSpeed to train your model via instruction tuning(and yes, the training process will be similar with that of alpaca).
Good luck!

**Comment by craggy-otake** [comment]
Thanks,
